class CONSTANTS:
    NEO_ADEPT = 'NeoAdept'
    NEO_CV = 'NeoCV'
    ENT_NOT_EXISTS='data set can be added or updated only for existing entities'
    DRS = 'Data retrieved successfully'
    DDS = 'Data deleted successfully'
    RPS='Resume uploaded successfully'
    NO_RES='No resume found'
    NO_ENT='No entity found'
    DAS = 'Data saved successfully'
    CAS = 'Entity added successfully'
    CUS = 'Entity updated successfully'
    DUS='Data set updated successfully'
    DSS= 'Data set added successfully'
    DSF='Pattern already exists'
    DEL_PAT= 'Data set deleted successfully'
    DEL_PAT_FAIL='delete pattern operation failed'
    PAT_SET_EMP='No pattern set found'
    MLS='Model loaded successfully'
    RES_PAT='Resume file saved successfully and new pattern_set added'
    RES_NOPAT='Resume file saved and no new patterns are added'
    FILE_ID_NO_EXISTS='The resume file with the id does not exists'
    SEF='File saving failed'
    ENTITY_LIST=['CERTIFICATIONS','COMPANY','ROLE','LANGUAGES','EDU','SKILL','MOBILE','EMAIL','EXPERIENCE','PERSON']
    REGISTER_USER_REQ_FIELDS = ['name', 'phone', 'email', 'role', 'client_id', 'status']
    REGISTER_USER_REQ_FIELDS_ADMIN = ['name', 'phone', 'email','status','role']
    STATUS = 'status'
    STATUS_CODE = 'status_code'
    SUCCESS = 'success'
    FAILED = 'failed'
    MESSAGE = 'message'
    ERR_CODE_MESSAGE_500 = 'Please contact administrator'
    NO_DATA_FOUND = 'No data found'
    SUCCESS_STATUS_CODE = 200
    ERROR_CODE=201
    DATA = "data"
    FUNCTION = 'function'
    SELECT = "SELECT "
    DISTINCT = "distinct "
    CASE = "CASE "
    WHEN = "WHEN "
    FROM = " FROM "
    LEFT_JOIN = " LEFT JOIN "
    JOIN = " JOIN "
    ON = " ON "
    WHERE = " WHERE "
    SPACE = " "
    TRUE = True
    FALSE = False
    NONE = None
    INSERT_QUERY = "INSERT INTO "
    VALUES = " VALUES "
    EMAIL ="email"
    ROLE ="role"
    _ID ="_id"
    ADMIN = "admin"
    UPDATE_QUERY = "UPDATE "
    SET_KEYWORD = " SET "
    Q_COUNT_COND = 'count(*) as count'
    PER_PAGE = 'per_page'
    PAGE = 'page'
    SORT_BY = 'sort_by'
    ORDER_BY = 'order_by'
    Q_ORDER_BY = ' ORDER BY '
    Q_OFFSET = ' OFFSET '  
    Q_LIMIT = ' LIMIT '  
    DESC = ' desc '
    SEARCH_BY = 'search_by'
    FILTER_BY = 'filter_by'
    AND = ' and '
    COUNT = 'count'
    CLIENT_NAME = 'client_name'
    CLIENT_ID = 'client_id'
    USER="user"
    USER_ID='_id'
    ADD='add'
    UPDATE='update'
    DELETE='delete'
    IS_DELETED='is_deleted'
    UPDATE_USER_REQ_FIELDS = ['name', 'phone','email','client_name','updated_by',]  # Fields that can be updated
    ORDER_BY_INVALID='invalid parameter for order_by'
    SORT_BY_INVALID='invalid parameter for sort_by'
    DOC_NOT_FOUND="Document not found"
    INVALID_PWD='Invalid password'
    PRS='Password reset successful'
    PCS='Password change successful'
    USER_ALREADY_EXISTS='User exists'
    LOGOUT='logout successful'
    PWD_RESET_FAIL='Could not change or reset the password'
    CRDTS_ERR='invalid input'
    USER_FAIL='User not found'
    INVALID_PWD='Invalid password'
    INVALID_OTP='Invalid OTP'
    OTP='OTP generated'
    OTP_VALID='OTP is valid'
    OTP_EXP='OTP expired'
    NO_ACTIVE_SUBSCRIPTION_ERR_MSG="Client not subscribed for current date"
    TOKEN_EXPIRED_MESSAGE = 'Token expired. Please login again'
    ADD_CLIENT_ERR_MSG1 = 'Only product-admin can add clients!'
    ADD_CLIENT_ERR_MSG3 = 'Only product-admin can add subscription!'
    UPDATE_CLIENT_ERR_MSG2 = 'Only product-admin can edit client details!'
    DELETE_CLIENT_ERR_MSG = "Only product-admin can delete clients!"
    DELETE_CLIENT_SUCCESS_MSG = "Client deleted successfully"
    COULD_NOT_DELETE_CLIENT = "Could not delete client!"
    GET_CLIENT_ERR_MSG = 'Only product-admin can view client details!'
    PRODUCT_ADMIN = 'product-admin'
    ADD_CLIENT_SUCCESS_MSG="Client added successfully"
    ADD_CLIENT_ERR_MSG2="Could not add client"
    CLIENT_EXISTS="Client already exists"
    CLIENT_ID_REQUIRED="client_id is required"
    CLIENT_NOT_FOUND="Client not found"
    UPDATE_CLIENT_SUCCESS_MSG="Client updated successfully"
    UPDATE_CLIENT_ERR_MSG1="Could not edit client details"
    GET_CLIENT_LOG_INFO1="request to get the client details"
    CLIENT_DETAILS="client_details"
    GET_CLIENT_LOG_INFO2="client details obtained"
    CLIENT_ID_MISSING="client_id is missing in request"
    INACTIVE="inactive"
    ACTIVE="active"
    CLIENT_ALREADY_INACTIVE="Client is already inactive"
    CLIENT_ALREADY_DELETED="Client is already deleted"
    SEND_MAIL_SUCCESS_MSG='Email sent and mail data stored successfully.'
    EMAIL_INFO="email_info"
    MAIL_HIST_LOG_INFO="request to get the email history details"
    LIST_GROUP="list_group"
    FILE_EMAIL_GROUPING="file_email_grouping"
    FILE_GROUP_VIEW="file_group_view"
    LIST_NAME='list_name'
    LIST_ID='list_id'
    LIST_NAME_MISSING='List name not provided'
    LIST_NAME_EXISTS='List name already exists'
    ADD_CONTACT_LIST_SUCCESS='Contact list group created successfully.'
    LIST_INFO_MISSING='list_name or list_id not provided'
    LIST_NOT_FOUND='List not found'
    UPDATE_LIST_SUCCESS="List name updated successfully"
    UPDATE_LIST_FAILED="Could not rename list"
    LIST_ID_MISSING='list_id not provided'
    DELETE_LIST_SUCCESS_MSG='List and associated documents deleted successfully'
    DELETE_LIST_SUCCESS_MSG1='List deleted successfully'
    FILE_IDS='file_ids'
    FILE_IDS_MISSING='file_ids not provided'
    ADD_FILE_GROUP_SUCCESS='file list added to group successfully.'
    REMOVE_CV_FROM_GRP_SUCCESS='CVs removed from group successfully.'
    NO_FILES_REMOVED='No files removed'
    USER_ID_MISSING="_id missing in request"
    USER_VIEW="user_view"
    GET_USER_LOG="user details obtained"
    ADD_USER_ERR1="Admin can add users only"
    ADD_USER_ERR2="User cannot add new users"
    USER_EXISTS="User with this email already exists"
    ADD_USER_SUCCESS="User registered successfully"
    USER_NOT_FOUND="User does not exists"
    UPDATE_USER_SUCCESS="User details updated successfully"
    UPDATE_USER_ERR="Cannot edit user from another client"
    UPDATE_USER_ERR1="Admin can edit users only"
    UPDATE_USER_ERR2="Users cannot update other users"
    DELETE_USER_ERR="Cannot delete user"
    USER_ALREADY_INACTIVE="User is already inactive"
    USER_ALREADY_DELETED="User is already deleted"
    DELETE_USER_SUCCESS="User deleted successfully"
    DELETE_USER_ERR1="Cannot delete user from different client"
    DELETE_USER_ERR2="Admin can delete users only"
    DELETE_CLIENT_AND_USERS_SUCCESS_MSG="Deleted client and associated users successfully"
    OVERLAPPING_SUBSCRIPTION_ERR_MSG="Existing subscriptions overlap with the dates provided"
    ADD_SUBSCRIPTION_SUCCESS_MSG="Subscription added successfully"
    ADD_SUBSCRIPTION_ERR_MSG="Could not add subscription"
    ADD_ROLE='Role saved successfully'
    ADD_WIDGET='Widget saved successfully'
    ADD_PAGE='Page saved successfully'
    ADD_MENU='Menu saved successfully'    
    ADD_SUB_MENU='sub_menu saved successfully'
    DEL_ROLE='Role deleted successfully'
    DEL_WIDGET='Widget deleted successfully'
    DEL_PAGE='Page deleted successfully'
    DEL_MENU='Menu deleted successfully'    
    DEL_SUB_MENU='sub_menu deleted successfully'
    ADD_FAILED = "Object insertion/updation failed"
    DEL_FAILED = "Object delete failed"    
    NO_FILE='No file found'
    CLIENT_NAME_MISSING_ERR_MSG="client_name is missing"
    API_URL_MISSING_ERR_MSG='api_url is missing'
    DOMAIN_MISSING_ERR_MSG='domain is missing'
    API_URL_EXISTS="api_url already exists"
    DOMAIN_EXISTS="domain already exists"
    EXCEL_NOT_VALID="Invalid excel.Please provide excel with valid column names"
    KEYS_TO_REMOVE = ['created_on', 'created_by', 'updated_on', 'updated_by']
    REQUIRED_FIELDS_MISSING = 'Required fields missing'
    UNAUTHORIZED_ERR_MSG = 'Unauthorized access'
    WIDGET_KEYS=['class_name','description','file_name','info','name','type']
    PAGE_KEYS=['class_name','description','router_link','info','name','widget_ids']
    MENU_KEYS=['name','icon','is_sub_menu']
    SUB_MENU_KEYS=['name','icon','page_id']
    ROLE_KEYS=['name','description','menu_ids']
    CLIENT_KEYS=['client_name','api_url','domain','status','db_name']
    USER_KEYS=['email','phone','role','name']
    FUNCTIONAL_ERR_STATUS_CODE = 201
    NO_CHANGES_FOUND = "No changes found"
    NO_DATA_ADDED = "No data added"
    FEW_RECORDS_NOT_DEL = "Records may be already deleted or tech issues to delete the record"  
    DUPLICATE_DATA = "Duplicate entries"
    SUBJECT_IS_MISSING = "Subject is missing"
    AUTHORIZATION_ERR = 'Not authorized to do this function!'
    ALLOWED_CV_EXTENSIONS =  {'doc', 'pdf', 'docx'}    
    UPDATE_DEL_ATTRIBUTES = ["created_by","created_on","_id"]
    OFFER = ['offered','offer accepted']
    INTERVIEW ='interview schedule'    
    MAP_CAN = 'Mapped candidates to the job successfully'
    DEL_CAN  = 'Deleted candidates from the job'
    UP_CAN = 'Updated candidate status successfully'
    DEL_JOB = 'Job deleted successfully'
    PRODUCT_USER ='product-user'
    CLIENT = 'client'
    UI_COLLECTIONS = ['WIDGET', 'PAGE','SUB_MENU', 'MENU','ROLE']# order should be maintained
    WIDGET_MANDATORY_EXCEL_KEYS = ['name','file_name']
    PAGE_MANDATORY_EXCEL_KEYS = ['router_link','widget_mapping']
    MENU_MANDATORY_EXCEL_KEYS = ['name']
    SUB_MENU_MANDATORY_EXCEL_KEYS = ['name','page_mapping']
    ROLE_MANDATORY_EXCEL_KEYS= ['name']
    CAN_STATUS_INITIAL_VALUE = 'Identified'
    JOINING_DATE ='joined'
    IGNORE_PERMISSION_API_LIST = []
    ROLE_PERMISSION_MANDATORY_EXCEL_KEYS = ['role_name','module','submodule_level_1','submodule_1_access']
    USER_DETAILS_KTR = ['notes', 'password', 'otp', 'otp_timestamp', 'token', 'entity_id', 'new_password', 'current_password',"db_name",'client_domain','client_name']
    ROLE_KTR =['menu_ids']
    MENU_KTR = ['page_id','sub_menu_ids']
    SUB_MENU_KTR =['page_id']
    PAGE_KTR = ['widget_ids']
    SQL="SQL"
    FILTERS="filters"